---
title: "Homework 1"
format: html
---

**Due:** Friday, January 23, 11:59pm on Canvas

**Instructions:** For mathematical work, you may choose to either hand-write your work and submit a PDF scan, or type your work using LaTeX and submit the resulting PDF. For computational work, include all code and R output necessary to answer the questions, and submit as an html or pdf on Canvas.

See the course website for a [homework template](https://sta711-s26.github.io/homework/hw_template.tex) file and [instructions](https://sta711-s26.github.io/homework/latex_instructions/) on getting started with LaTeX and Overleaf.

## Probability review

The purpose of these questions is to review some key concepts which will be useful in STA 711.
Review the material in Casella & Berger, chapters 1, 2, 3.1–3.3, and 4.1–4.5; some of the key points are summarized in [supplementary course notes](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html).

Choose **four** of the following questions to submit from the supplementary notes (I suggest you practice topics with which you feel less comfortable).

1. [Exercise A.1](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html#exr-prob1)

2. [Exercise A.2](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html#exr-prob2)

3. [Exercise A.3](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html#exr-prob3)

4. [Exercise A.4](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html#exr-prob4)

5. [Exercise A.5](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html#exr-prob5)

6. [Exercise A.6](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html#exr-prob6)

7. [Exercise A.7](https://ciaran-evans.quarto.pub/sta-711-notes/probability_review.html#exr-prob7)

## Regression

Read [Section 1.3.3](https://ciaran-evans.quarto.pub/sta-711-notes/linear_regression.html#weighted-least-squares) in the supplementary notes. Then answer the following question.

8. [Exercise 1.1](https://ciaran-evans.quarto.pub/sta-711-notes/linear_regression.html#exr-linear1)

## Simulation

A simulation study allows us investigate statistical questions by simulating data under a variety of different conditions, and seeing how the statistical methods behave under these different conditions. We will use simulations pretty regularly in STA 711.

The paper ["Using simulation studies to evaluate statistical methods"](https://onlinelibrary.wiley.com/doi/10.1002/sim.8086) (Morris *et al.* 2019) provides a good overview of the important steps in designing a simulation study. Read sections 1 (Introduction) and 3 (Planning simulation studies) of the paper, and the [appendix on simulations](https://ciaran-evans.quarto.pub/sta-711-notes/simulations.html) in the supplementary notes.

Then answer the following question.

9. [Exercise 1.3](https://ciaran-evans.quarto.pub/sta-711-notes/linear_regression.html#exr-linear3)





