---
title: "Comparing hypothesis tests"
author: "Ciaran Evans"
output: beamer_presentation
---

## Hypothesis testing so far

**General idea:** 

1. Have a parameter of interest, $\boldsymbol{\theta}$, and two competing hypotheses/models:
$$H_0: \boldsymbol{\theta} \in \Theta_0 \hspace{1cm} H_A: \boldsymbol{\theta} \in \Theta_1$$
2. Find a statistic $T(\boldsymbol{X})$ that we expect to be "big" under $H_A$ and "small" under $H_0$

3. Reject $H_0$ when $T(\boldsymbol{X})$ is "big". Specific rejection threshold chosen so that $\sup \limits_{\theta \in \Theta_0} \beta(\theta) \leq \alpha$. And ideally want $\beta(\theta)$ large for $\theta \in \Theta_1$.

**That's it!** And there are *many* possible tests (and test statistics). The hard task is:

* Finding test statistics that behave the way we want (known distribution under $H_0$)
* Which test should we choose? I.e. which test has good power?

## Some general-purpose tests

**Wald test:** Test hypotheses about a parameter $\boldsymbol{\theta}$ using asymptotic normality of estimator $\widehat{\boldsymbol{\theta}}$

\vspace{2cm}

**Likelihood ratio test:** Test hypotheses about a parameter $\boldsymbol{\theta}$ using likelihood ratio

* $H_0: \boldsymbol{\theta} = \boldsymbol{\theta}_0$ vs. $H_A: \boldsymbol{\theta} = \boldsymbol{\theta}_1$ $\Longrightarrow$ Reject when $\dfrac{L(\boldsymbol{\theta}_1 | \boldsymbol{X})}{L(\boldsymbol{\theta}_0 | \boldsymbol{X})} > k$
* If distribution has MLR in a statistic $T(\boldsymbol{X})$, UMP test of $H_0: \theta \leq \theta_0$ vs. $H_A: \theta > \theta_0$ rejects when $T(\boldsymbol{X}) > t_0$
* General case: reject when $\dfrac{\sup \limits_{\boldsymbol{\theta} \in \Theta_0} L(\boldsymbol{\theta} | \boldsymbol{X})}{\sup \limits_{\boldsymbol{\theta} \in \Theta} L(\boldsymbol{\theta} | \boldsymbol{X})} \leq k$

## Wald and likelihood ratio tests in the wild

**Wald tests:**

* Could view $t$ tests as a variant of Wald tests that accounts for estimating the population variance
* One-sample tests, two-sampled tests, paired tests, etc.
* Tests for means and proportions
* Tests for individual regression coefficients (useful for testing directionality)
* Tests for $M$-estimators (likelihood doesn't apply)

**Likelihood ratio tests:**

* Chi-squared tests (independence, etc.)
* ANOVA, linear regression $F$ tests
* Comparing nested models for GLMs
* In practice usually rely on asymptotic result $-2 \log \Lambda \approx \chi^2_{d - d_0}$ under $H_0$

## Comparing Wald and LRT statistics

Suppose we observe data $X_1,...,X_n$ from some distribution with parameter $\boldsymbol{\theta} \in \mathbb{R}^q$, and we wish to test

$$H_0: \boldsymbol{\theta} = \boldsymbol{\theta}_0 \hspace{1cm} H_A: \boldsymbol{\theta} \neq \boldsymbol{\theta}_0$$

Consider three possible scenarios:

* $H_0$ is true: $\boldsymbol{\theta} =$
* $H_A$ is true, **fixed** alternative: $\boldsymbol{\theta} =$
* $H_A$ is true, **local** alternative: $\boldsymbol{\theta} =$

\vspace{3cm}

## Comparing Wald and LRT statistics

Under $H_0$, or for a local alternative $\boldsymbol{\theta} = \boldsymbol{\theta}_0 + \frac{\boldsymbol{h}}{\sqrt{n}}$, Wald and LRT are asymptotically equivalent as $n \to \infty$ (under certain regularity conditions).

\vspace{6cm}

## Power under a local alternative

Recall asymptotic normality of the MLE: $\widehat{\boldsymbol{\theta}} \approx N(\boldsymbol{\theta}, \mathcal{I}_n^{-1}(\boldsymbol{\theta}))$

Suppose we test $H_0: \boldsymbol{\theta} = \boldsymbol{\theta}_0$ vs. $H_A: \boldsymbol{\theta} \neq \boldsymbol{\theta}_0$.
$$W = \hspace{5cm}$$
Under $H_0$, $W \approx \chi^2_q$

\vspace{4cm}

## Comparing other hypothesis tests

Suppose we have $X_1,...,X_n$ iid from a symmetric distribution with mean and median $\theta$. We wish to test
$$H_0: \theta = 0 \hspace{1cm} H_A: \theta > 0$$
Two asymptotic results:
$$\sqrt{n}(\overline{X}_n - \theta) \overset{d}{\to} N(0, \sigma^2) \hspace{1cm} \sqrt{n}(M_n - \theta) \overset{d}{\to} N\left(0, \frac{1}{4 f^2(\theta)}\right)$$

\vspace{6cm}

## Comparing other hypothesis tests

$$\sqrt{n}(\overline{X}_n - \theta) \overset{d}{\to} N(0, \sigma^2) \hspace{1cm} \sqrt{n}(M_n - \theta) \overset{d}{\to} N\left(0, \frac{1}{4 f^2(\theta)}\right)$$

```{r, echo=F, message=F, warning=F, fig.width=7, fig.height=3.5}
library(tidyverse)
library(patchwork)

alpha <- 0.05
za <- qnorm(alpha, lower.tail=F)
sigma <- 2
n <- 20
power_mean <- function(theta){
  1 - pnorm(za - sqrt(n)*theta/sigma)
}

power_median <- function(theta){
  1 - pnorm(za - 2*sqrt(n)*theta*dnorm(0, sd = sigma))
}

theta_vals <- seq(0, 3, 0.1)
p1 <- data.frame(theta = c(theta_vals, theta_vals),
           power = c(power_mean(theta_vals), power_median(theta_vals)),
           type = rep(c("mean", "median"), each=length(theta_vals))) |>
  ggplot(aes(x = theta, y = power, color = type, lty=type)) +
  geom_line() +
  theme_bw() +
  labs(title = "Normal distribution")




alpha <- 0.05
za <- qnorm(alpha, lower.tail=F)
b <- 2
n <- 20
power_mean <- function(theta){
  1 - pnorm(za - sqrt(n)*theta/sqrt(2*b^2))
}

power_median <- function(theta){
  1 - pnorm(za - 2*sqrt(n)*theta*VGAM::dlaplace(0, scale=b))
}

theta_vals <- seq(0, 3, 0.1)
p2 <- data.frame(theta = c(theta_vals, theta_vals),
           power = c(power_mean(theta_vals), power_median(theta_vals)),
           type = rep(c("mean", "median"), each=length(theta_vals))) |>
  ggplot(aes(x = theta, y = power, color = type, lty=type)) +
  geom_line() +
  theme_bw() +
  labs(title = "Laplace distribution")

p1 + p2 + plot_layout(guides = 'collect') & theme(legend.position = 'bottom')
```

\vspace{3cm}

## Local asymptotic power

$$H_0: \theta = 0 \hspace{1cm} H_A: \theta > 0$$

Using the mean: $\beta_{mean}(\theta) \approx \Phi\left(  \dfrac{\theta\sqrt{n}}{\sigma} - z_\alpha \right)$

Using the median: $\beta_{med}(\theta) \approx \Phi \left(2  \theta f_\theta(\theta) \sqrt{n} - z_\alpha \right)$

\vspace{5cm}




