---
title: "Likelihood ratio tests"
author: "Ciaran Evans"
output: beamer_presentation
---

## Last time: Likelihood ratio test

Suppose we have a sample $\mathbf{X} = (X_1,...,X_n)$ from some distribution with probability function $f(x|\boldsymbol{\theta})$, with parameter $\boldsymbol{\theta} \in \mathbb{R}^d$. We wish to test
$$H_0: \boldsymbol{\theta} \in \Theta_0 \hspace{1cm} H_A: \boldsymbol{\theta} \in \Theta_1$$
The **likelihood ratio test** (LRT) of these hypotheses rejects $H_0$ when:
$$\Lambda = \dfrac{\sup \limits_{\boldsymbol{\theta} \in \Theta_0} L(\boldsymbol{\theta} | \boldsymbol{X})}{\sup \limits_{\boldsymbol{\theta} \in \Theta} L(\boldsymbol{\theta} | \boldsymbol{X})} \leq k$$

\vspace{4cm}

## Asymptotics of the LRT: scalar case

Suppose we have an iid sample $\mathbf{X} = (X_1,...,X_n)$ from some distribution with probability function $f(x|\theta)$, with parameter $\theta \in \mathbb{R}$. We wish to test
$$H_0: \theta = \theta_0 \hspace{1cm} H_A: \theta \neq \theta_0$$

**Theorem:** Under $H_0$ (and assuming required regularity conditions),

\vspace{6cm}

## Asymptotics of the LRT: general case

Suppose we have an iid sample $\mathbf{X} = (X_1,...,X_n)$ from some distribution with probability function $f(x|\boldsymbol{\theta})$, with parameter $\boldsymbol{\theta} \in \Theta \subseteq \mathbb{R}^d$. We wish to test
$$H_0: \boldsymbol{\theta} \in \Theta_0 \hspace{1cm} H_A: \boldsymbol{\theta} \in \Theta_1$$
Let $d = \text{dim}(\Theta)$ be the number of free parameters specified by $\Theta$, and let $d_0$ be the number of free parameters specified by $\Theta_0$.

**Theorem:** Under $H_0$ (and assuming required regularity conditions),

\vspace{6cm}

