---
title: "Class activity"
format: html
editor: source
---

# Hypothesis testing with the Titanic data

In this class activity, we will construct confidence intervals for quantities of interest in the titanic data. Let $Y_i$ denote whether passenger $i$ survived. We will use the model

$$Y_i \sim Bernoulli(p_i)$$

$$\log \left( \dfrac{p_i}{1 - p_i} \right) = \beta_0 + \beta_1 Sex_i + \beta_2 Age_i + \beta_3 SecondClass_i + \beta_4 ThirdClass_i$$

The Titanic data can be imported into R with

```{r, eval=F}
titanic <- read.csv("https://sta711-s26.github.io/homework/Titanic.csv")
```


## Questions

1. Fit the logistic regression model in R.

2. Use a Wald test to test 

$$H_0: \beta_3 = \beta_4 = 0 \hspace{1cm} H_A: \text{at least one of } \beta_3, \beta_4 \neq 0$$

Recall that the variance-covariance matrix can be extracted with the `vcov(...)` function.

## Questions: Wald test for a contrast

The null hypothesis $H_0: \beta_3 = \beta_4 = 0$ asks whether there is any relationship between passenger class and survival, after accounting for Sex and Age. But now suppose you want to ask a different question: is there a difference in survival between second and third class passengers? 

Neither $\beta_3$ nor $\beta_4$ directly addresses this question. Instead, we want to compare $\beta_3$ and $\beta_4$ to *each other*; our hypotheses are

$$H_0: \beta_3 - \beta_4 = 0 \hspace{1cm} H_A: \beta_3 - \beta_4 \neq 0$$

How should we test these hypotheses? Once again, we can use a Wald test!


3. Find a matrix ${\bf C}$ such that ${\bf C}\beta = \beta_3 - \beta_4$.

The difference $\beta_3 - \beta_4$ is called a *contrast*, and is another example of a linear transformation of $\beta$.


4. Calculate the Wald test statistic and p-value for $H_0: \beta_3 - \beta_4 = 0$.

